MAX_LEN: 512
N: 6
args: !!python/object:argparse.Namespace
  classification_type: binary
  d_model: 512
  data_sample: 1.0
  early_stopping_rounds: 4
  epochs: 30
  eval_batch_size: 16
  lambda_: 0.001
  lr: 0.0005
  max_grad_norm: 5
  max_lr: 0.5
  max_text_len: 512
  model_save_path: ../models/imdb/
  n_experts: 4
  n_layers: 6
  n_warmup: 4000
  pooling: mean
  seed: 42
  test_data_file: ../data/imdb_data_test.csv
  train_batch_size: 16
  train_data_file: ../data/imdb_data_train.csv
  use_eigen: false
  use_random_features: 'true'
  wandb_logging: false
  wandb_project_name: IMDb Classification
classification_type: binary
d_model: 512
n_experts: 4
n_out: 1
pooling: mean
random_features: true
src_vocab: 30522
use_eigen: false
